//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibG9jYWwuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi9zcmMvbG9jYWwuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7O0FBQUE7Q0FBQSxJQUFBLENBQUE7Q0FBQTtDQUFBLENBQUEsQ0FBUSxDQUFDLENBQVQsRUFBa0I7O0NBQWxCLENBRUEsQ0FDQyxFQURJO0NBQ0osQ0FBVyxDQUFBLENBQVYsSUFBQSxDQUFVO0NBQ1IsR0FBQyxFQUFELEdBQUE7Q0FDQyxHQUFBLENBQUQsSUFBQSxJQUFBO0NBRkgsSUFBVztDQUFYLENBSVksQ0FBQSxDQUFYLEtBQUE7Q0FDRSxLQUFBLElBQUE7Q0FBQSxFQUFTLENBQUksRUFBYixHQUFTO0NBQ0ksRUFBYyxDQUFiLEtBQUQsR0FBQSxDQUFiO0NBTkgsSUFJWTtDQUpaLENBUVksQ0FBQSxDQUFYLEtBQUE7Q0FDRSxLQUFBLElBQUE7Q0FBQSxFQUFTLENBQWMsRUFBdkIsR0FBc0IsR0FBQTtDQUNyQixDQUFELEVBQUMsRUFBUSxDQUFULE1BQUE7Q0FBcUIsQ0FBUyxFQUFULENBQUUsR0FBQTtDQUZkLE9BRVQ7Q0FWSCxJQVFZO0NBWGIsR0FBQTs7O0NBZVEsRUFBVSxDQUFsQixDQUF1QixDQUFqQixDQUFOO0lBZkE7Q0FBQSIsInNvdXJjZXNDb250ZW50IjpbIlNwaW5lID0gQFNwaW5lIG9yIHJlcXVpcmUoJ3NwaW5lJylcblxuU3BpbmUuTW9kZWwuTG9jYWwgPVxuICBleHRlbmRlZDogLT5cbiAgICBAY2hhbmdlIEBzYXZlTG9jYWxcbiAgICBAZmV0Y2ggQGxvYWRMb2NhbFxuXG4gIHNhdmVMb2NhbDogLT5cbiAgICByZXN1bHQgPSBKU09OLnN0cmluZ2lmeShAKVxuICAgIGxvY2FsU3RvcmFnZVtAY2xhc3NOYW1lXSA9IHJlc3VsdFxuXG4gIGxvYWRMb2NhbDogLT5cbiAgICByZXN1bHQgPSBsb2NhbFN0b3JhZ2VbQGNsYXNzTmFtZV1cbiAgICBAcmVmcmVzaChyZXN1bHQgb3IgW10sIGNsZWFyOiB0cnVlKVxuXG5tb2R1bGU/LmV4cG9ydHMgPSBTcGluZS5Nb2RlbC5Mb2NhbCJdfQ==
// Generated by CoffeeScript 1.6.1
(function() {
  var Spine;

  Spine = this.Spine || require('spine');

  Spine.Model.Local = {
    extended: function() {
      this.change(this.saveLocal);
      return this.fetch(this.loadLocal);
    },
    saveLocal: function() {
      var result;
      result = JSON.stringify(this);
      return localStorage[this.className] = result;
    },
    loadLocal: function() {
      var result;
      result = localStorage[this.className];
      return this.refresh(result || [], {
        clear: true
      });
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Spine.Model.Local;
  }

}).call(this);
