// Generated by CoffeeScript 1.6.2
(function() {
  (function(root, factory) {
    if (typeof exports === 'object') {
      return module.exports = factory(require('Spine'));
    } else if (typeof define === 'function' && define.amd) {
      return define(['Spine'], factory);
    } else {
      return factory(root.Spine);
    }
  })(this, function(Spine) {
    Spine.Model.Local = {
      extended: function() {
        this.change(this.saveLocal);
        return this.fetch(this.loadLocal);
      },
      saveLocal: function() {
        var result;

        result = JSON.stringify(this);
        return localStorage[this.className] = result;
      },
      loadLocal: function() {
        var result;

        result = localStorage[this.className];
        return this.refresh(result || [], {
          clear: true
        });
      }
    };
    return Spine.Model.Local;
  });

}).call(this);
